import os

DEFAULT_SYSTEM_TEXT = """
You are a bot in a slack chat room.
"""
SYSTEM_TEXT_ZORK = os.environ.get("OPENAI_SYSTEM_TEXT_ZORK", DEFAULT_SYSTEM_TEXT)
SYSTEM_TEXT_JEOPARDY = os.environ.get("OPENAI_SYSTEM_TEXT_JEOPARDY", DEFAULT_SYSTEM_TEXT)
SYSTEM_TEXT_MUD = os.environ.get("OPENAI_SYSTEM_TEXT_MUD", DEFAULT_SYSTEM_TEXT)

DEFAULT_OPENAI_TIMEOUT_SECONDS = 30
OPENAI_TIMEOUT_SECONDS = int(
    os.environ.get("OPENAI_TIMEOUT_SECONDS", DEFAULT_OPENAI_TIMEOUT_SECONDS)
)
DEFAULT_OPENAI_MODEL = "gpt-3.5-turbo"
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)
USE_SLACK_LANGUAGE = os.environ.get("USE_SLACK_LANGUAGE", "true") == "true"
SLACK_APP_LOG_LEVEL = os.environ.get("SLACK_APP_LOG_LEVEL", "DEBUG")